### ISSUE TITLE
Undefined global 'Bitstring'

### ISSUE THREAD

**Issue by galenmarchetti** [njc46/alpha-beta-gamma-Evolution#2]
```bash
~./compile
```

**File "load.ml", line 1:
Error: Error while linking load.cmo:
Reference to undefined global `Bitstring'**

Is this the same error that @njc46 had with ocamlc that cs3110 let slide?

**Comment by galenmarchetti** [comment]
Either way, I think https://github.com/njc46/alpha-beta-gamma-Evolution/pull/3 resolves this

**Comment by njc46** [comment]
i have synced and had no issues?

**Comment by galenmarchetti** [comment]
Cool, then https://github.com/njc46/alpha-beta-gamma-Evolution/pull/3 did the trick. Closing issue
